apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSetting
metadata:
  name: finos-setting
  namespace: openshift-compliance
schedule: "5 * * * *"
rawResultStorage:
    size: "2Gi"
    rotation: 5
roles:
  - worker
  - master
