apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2022-07-08T08:08:43Z"
    generation: 2
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 57050271-afec-463f-81e5-78f7089805ad
    resourceVersion: "120271"
    uid: a9270143-99a1-43f7-ab89-519d5705d740
  spec:
    identityProviders:
    - name: my_htpasswd_provider 
      mappingMethod: claim 
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpass-secret 
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
