apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec: # >>>> the following lines should be added <<<<
  identityProviders:
  - name: my_htpasswd_provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret 
