name: terraform fmt check

on:
  push:
    paths:
      - ".github/workflows/terraform.yml"
      - "**/*terraform*/**"
      - "**.tf"
      - "**.tfvars"
      - "!**.md"
  pull_request:
    paths:
      - ".github/workflows/terraform.yml"
      - "**/*terraform*/**"
      - "**.tf"
      - "**.tfvars"
      - "!**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        # Long commit hash of v1.2.1
        uses: hashicorp/setup-terraform@d22444889af304a44b997011fbabb81ff705a7b4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
